/* app-devices.js — قسم الأجهزة: نموذج الإضافة/التعديل، الحفظ، العرض، بروفايل الجهاز. */
function initDevices(){let f=document.getElementById("deviceForm");if(!f)return;let q=new URLSearchParams(location.search),editId=q.get("edit"),existing=editId?arr(K.d).find(x=>x.id===editId):null;fillCustomer(dCustomer,existing?.customerId||q.get("customer")||"");fillTypes(dType,existing?.type||"");fillBrands(dBrand,existing?.brand||"");function syncAddr(){fillAddress(dAddress,dCustomer.value,existing?.addressKey||"main")}function syncCat(){fillCats(dCategory,dType.value,existing?.category||"")}dCustomer.onchange=()=>{syncAddr()};dType.onchange=syncCat;dPhoto.onchange=previewImage;syncAddr();syncCat();if(existing){dModel.value=existing.model||"";dDesc.value=existing.desc||"";if(existing.photo){(async()=>{let src=window.ImageStore?await window.ImageStore.resolveSrc(existing.photo):existing.photo;if(src)photoPreview.innerHTML=`<img class="photo" src="${src}">`})()}document.querySelector("#deviceForm").classList.remove("hidden");document.getElementById("deviceSubmitBtn").textContent="💾 حفظ التعديلات وفتح الملف"}else if(q.get("customer")||q.get("add")){document.querySelector("#deviceForm").classList.remove("hidden")}f.onsubmit=e=>saveDevice(e,existing);document.getElementById("deviceSearch")?.addEventListener("input",renderDevices);if(document.getElementById("deviceCenterFilter")){let cf=document.getElementById("deviceCenterFilter");cf.innerHTML='<option value="">🗺️ كل المراكز</option>'+(settings().centers||[]).map(x=>`<option>${esc(x)}</option>`).join("");cf.onchange=renderDevices}renderDevices()}
function previewImage(e){let file=e.target.files[0],out=document.getElementById("photoPreview");if(!file)return;let r=new FileReader();r.onload=()=>out.innerHTML=`<img class="photo" src="${r.result}">`;r.readAsDataURL(file)}
// نفس مبدأ الفصل: قراءة الفورم (بما فيها تحويل الصورة غير المتزامن) في دالة،
// ومنطق الحفظ الصِرف في دالة تانية بترجع {ok, device} بدل ما تتحكم في التنقل بنفسها.
async function collectDeviceFormData(existing){let photo=existing?.photo||"";if(dPhoto.files[0]){let dataURL=await imageToDataURL(dPhoto.files[0]);photo=window.ImageStore?await window.ImageStore.save(dataURL,existing?.photo):dataURL}return{customerId:dCustomer.value,addressKey:dAddress.value,type:dType.value,category:dCategory.value,brand:dBrand.value,model:dModel.value,desc:dDesc.value,photo}}
function persistDeviceRecord(formData,existing){let d=existing||{id:id(),createdAt:new Date().toISOString()};Object.assign(d,formData);let a=arr(K.d);if(!saveJSONSafe(K.d,existing?a.map(x=>x.id===d.id?d:x):a.concat(d)))return{ok:false};return{ok:true,device:d}}
async function saveDevice(e,existing=null){e.preventDefault();try{let formData=await collectDeviceFormData(existing);let result=persistDeviceRecord(formData,existing);if(!result.ok)return;location.href=`device.html?id=${result.device.id}`}catch(err){alert("تعذر حفظ صورة الجهاز. جرّب صورة أخرى أصغر.")}}
// النسخة الأساسية — بيتم استبدالها لاحقًا في devices.html/device.html بنسخة
// workshop-mini-enhancements.js ثم workshop-mini-simple-ui.js (آخر واحد هو الشغال فعليًا).
function renderDevices(){let el=document.getElementById("deviceList");if(!el)return;let q=(document.getElementById("deviceSearch")?.value||"").toLowerCase().trim();let cf=document.getElementById("deviceCenterFilter")?.value||"";let a=arr(K.d).filter(d=>{let c=arr(K.c).find(x=>x.id===d.customerId)||{};let text=(c.name||"")+" "+(c.phone||"")+" "+addressText(c.mainAddress||{})+" "+addressText(c.extraAddress||{});return text.toLowerCase().includes(q)&&(!cf||c.mainAddress?.center===cf)});el.innerHTML=a.length?a.map(d=>`<div class="item record-card ps-context-target" data-ps-title="${esc(d.type)} ${esc(d.brand)}"><div class="card-side-actions"><a class="primary small-btn" href="device.html?id=${d.id}">فتح 360°</a><button class="danger-btn small-btn" type="button" onclick="deleteDeviceRecord('${d.id}')">🗑️ حذف</button></div><div class="record-main"><div class="item-head"><a href="device.html?id=${d.id}"><b>🔧 ${esc(d.type)} — ${esc(d.brand)}</b></a><span class="badge">${esc(customerName(d.customerId))}</span></div><div>📍 ${esc(addressText((arr(K.c).find(c=>c.id===d.customerId)||{}).mainAddress||{}))}</div><div>${esc(d.category)} • ${esc(d.model||"—")}</div></div></div>`).join(""):'<div class="item">لا توجد أجهزة.</div>'}

async function deviceProfile(){let el=document.getElementById("deviceProfile");if(!el)return;let d=arr(K.d).find(x=>x.id===new URLSearchParams(location.search).get("id"));if(!d){el.innerHTML="<div class='item'>الجهاز غير موجود.</div>";return}let rs=arr(K.r).filter(r=>r.deviceId===d.id);el.innerHTML=`<div class="profile ps-context-target" data-ps-title="${esc(d.type)} — ${esc(d.brand)}"><div class="page-head"><h1 class="profile-title">🔧 ${esc(d.type)} — ${esc(d.brand)}</h1><div class="compact-actions"><button class="secondary" onclick="editDevice('${d.id}')">✏️ تعديل</button>${psActions(d.type+" — "+d.brand)}<a class="primary" href="requests.html?customer=${d.customerId}&device=${d.id}">➕ أمر شغل</a></div></div><div class="profile-grid"><div class="kv"><b>👤 العميل</b><a href="customer.html?id=${d.customerId}">${esc(customerName(d.customerId))}</a></div><div class="kv"><b>📞 التليفون</b>${contactLinksHtml((arr(K.c).find(c=>c.id===d.customerId)||{}).phone)}</div><div class="kv"><b>📍 العنوان</b>${esc(addressText((arr(K.c).find(c=>c.id===d.customerId)||{}).mainAddress||{}))}</div><div class="kv"><b>النوع / التصنيف</b>${esc(d.type)} / ${esc(d.category)}</div><div class="kv"><b>الموديل</b>${esc(d.model)||"—"}</div></div><div id="deviceProfilePhoto"></div><h2>🛠️ سجل أوامر الشغل</h2>${rs.length?rs.map(r=>`<div class="item"><a href="request.html?id=${r.id}"><b>${esc(r.no)}</b></a> <span class="badge">${esc(r.status)}</span>${r.workshopStatus&&r.workshopStatus!=="غير مطلوب"?`<span class="badge workshop-badge">🏭 ${esc(r.workshopStatus)}</span>`:""}<div>${esc(r.fault)}</div></div>`).join(""):"<div class='item'>لا يوجد سجل.</div>"}</div>`;if(d.photo){let src=window.ImageStore?await window.ImageStore.resolveSrc(d.photo):d.photo;let ph=document.getElementById("deviceProfilePhoto");if(ph&&src)ph.innerHTML=`<img class="photo" src="${src}">`}}
