/* app-parts.js — قسم المخزن/قطع الغيار: كشف التكرار، الحذف/الأرشفة، النموذج، الحفظ، العرض، البروفايل. */
function normalizePartText(v){
  return String(v||"").toLowerCase().normalize("NFKC")
    .replace(/[\u064B-\u065F\u0670]/g,"")
    .replace(/[أإآ]/g,"ا").replace(/ة/g,"ه").replace(/[ـ]/g,"")
    .replace(/[٠-٩]/g,d=>String(d.charCodeAt(0)-0x0660))
    .replace(/[۰-۹]/g,d=>String(d.charCodeAt(0)-0x06F0))
    .replace(/[\s\-_./\\]+/g,"").trim();
}
function findDuplicatePartName(name,excludeId){const n=normalizePartText(name);if(!n)return null;return arr(K.p).find(p=>String(p.id)!==String(excludeId||"")&&!p.archived&&normalizePartText(p.name)===n)||null;}
function findSimilarPartNames(name,excludeId,limit){
  const n=normalizePartText(name);if(!n)return [];
  return arr(K.p)
    .filter(p=>String(p.id)!==String(excludeId||"")&&!p.archived&&p.name)
    .filter(p=>{const pn=normalizePartText(p.name);return pn!==n&&pn.startsWith(n);})
    .map(p=>p.name)
    .slice(0,limit||8);
}
function findDuplicatePartCode(code,excludeId){const n=String(code||"").trim().toLowerCase();if(!n)return null;return arr(K.p).find(p=>String(p.id)!==String(excludeId||"")&&!p.archived&&String(p.code||"").trim().toLowerCase()===n)||null;}
function deletePartRecord(pid){const all=arr(K.p),p=all.find(x=>x.id===pid);if(!p)return;const usedInOrders=arr(K.r).filter(r=>(r.parts||[]).some(x=>x.partId===pid));const movements=arr(K.m).filter(m=>m.partId===pid);if(usedInOrders.length){if(!p.archived&&confirm(`⚠️ الصنف «${p.name||""}» مستخدم في ${usedInOrders.length} أمر شغل سابق.\n\nحذفه سيكسر تاريخ أوامر الشغل، لذلك الأفضل أرشفته بدل حذفه.\n\nموافق = أرشفة الصنف وإخفاؤه من المخزن.`)){p.archived=true;p.archivedAt=new Date().toISOString();put(K.p,all);renderParts?.();alert("تمت أرشفة الصنف وسيظل محفوظًا داخل تاريخ أوامر الشغل.");}else if(p.archived){alert("الصنف مؤرشف بالفعل وما زال مرتبطًا بتاريخ أوامر شغل.");}return;}if(!confirm(`حذف الصنف «${p.name||""}» نهائيًا؟\n\nالكمية الحالية: ${+p.qty||0}\nحركات المخزن المرتبطة: ${movements.length}`))return;put(K.p,all.filter(x=>x.id!==pid));if(window.ImageStore?.delete&&p.photo)window.ImageStore.delete(p.photo);if(movements.length)put(K.m,arr(K.m).filter(m=>m.partId!==pid));refreshAllScreens?.();renderParts?.();if(document.getElementById("partProfile"))location.href="inventory.html";}
function restorePartRecord(pid){const all=arr(K.p),p=all.find(x=>x.id===pid);if(!p)return;p.archived=false;p.archivedAt="";put(K.p,all);renderParts?.();location.href="inventory.html";}

function initParts(){let f=document.getElementById("partForm");if(!f)return;let q=new URLSearchParams(location.search),editId=q.get("edit"),existing=editId?arr(K.p).find(x=>x.id===editId):null;fillPartCats(pCategory,existing?.category||"");pPhoto.onchange=e=>previewPart(e);if(existing){pName.value=existing.name||"";pCode.value=existing.code||"";pLocation.value=existing.location||"";pQty.value=existing.qty||0;pMin.value=existing.min||0;pBuy.value=existing.buy||0;pUse.value=existing.use||0;if(existing.photo){(async()=>{let src=window.ImageStore?await window.ImageStore.resolveSrc(existing.photo):existing.photo;if(src)partPhotoPreview.innerHTML=`<img class="photo" src="${src}">`})()}f.classList.remove("hidden");f.querySelector(".primary").textContent="💾 حفظ التعديلات وفتح الملف"}f.onsubmit=async e=>{e.preventDefault();const dup=findDuplicatePartName(pName.value,existing?.id);if(dup){alert(`⚠️ الصنف «${dup.name}» موجود بالفعل بنفس الاسم.\\n\\nاستخدم الصنف الموجود أو غيّر الاسم.`);pName.focus();return;}const dupCode=findDuplicatePartCode(pCode.value,existing?.id);if(dupCode){alert(`⚠️ كود الصنف «${dupCode.code}» مستخدم بالفعل مع «${dupCode.name}».\\n\\nاستخدم كودًا مختلفًا.`);pCode.focus();return;}await savePart(e,existing);};const partDuplicateHint=document.getElementById("partDuplicateHint");const checkPartDuplicate=()=>{if(!partDuplicateHint)return;const dn=findDuplicatePartName(pName.value,existing?.id),dc=findDuplicatePartCode(pCode.value,existing?.id);if(dn){partDuplicateHint.innerHTML=`⚠️ يوجد صنف بنفس الاسم بالضبط: <b>${esc(dn.name)}</b> — لن يسمح النظام بإضافة نسخة ثانية منه.`;partDuplicateHint.className="hint negative";return;}if(dc){partDuplicateHint.innerHTML=`⚠️ الكود مستخدم بالفعل مع: <b>${esc(dc.name)}</b> — اختر كودًا مختلفًا.`;partDuplicateHint.className="hint negative";return;}const similar=findSimilarPartNames(pName.value,existing?.id);if(similar.length){partDuplicateHint.innerHTML=`ℹ️ توجد أصناف بأسماء قريبة من هذا الاسم: ${similar.map(x=>`<b>${esc(x)}</b>`).join("، ")}. تأكد أن الصنف الذي تكتبه ليس نفسه قبل الحفظ.`;partDuplicateHint.className="hint";return;}partDuplicateHint.textContent="";partDuplicateHint.className="hint";};pName.addEventListener("input",checkPartDuplicate);pCode.addEventListener("input",checkPartDuplicate);partSearch.oninput=renderParts;renderParts()}
function fillPartCats(el,selected=""){el.innerHTML='<option value="">اختر التصنيف</option>'+settings().partCats.map(x=>`<option ${x===selected?"selected":""}>${esc(x)}</option>`).join("")}
function previewPart(e){let f=e.target.files[0];if(!f)return;imageToDataURL(f).then(x=>{partPhotoPreview.innerHTML=`<img class="photo" src="${x}">`;partPhotoPreview.dataset.image=x})}
async function collectPartFormData(existing){let photo=existing?.photo||"";if(pPhoto.files[0]){let dataURL=await imageToDataURL(pPhoto.files[0]);photo=window.ImageStore?await window.ImageStore.save(dataURL,existing?.photo):dataURL}return{name:pName.value,code:pCode.value,category:pCategory.value,location:pLocation.value,qty:+pQty.value||0,min:+pMin.value||0,buy:+pBuy.value||0,use:+pUse.value||0,photo}}
function persistPartRecord(formData,existing){let p=existing||{id:id(),createdAt:new Date().toISOString()};Object.assign(p,formData);let a=arr(K.p);if(!saveJSONSafe(K.p,existing?a.map(x=>x.id===p.id?p:x):a.concat(p)))return{ok:false};return{ok:true,part:p}}
async function savePart(e,existing=null){e.preventDefault();try{let formData=await collectPartFormData(existing);let result=persistPartRecord(formData,existing);if(!result.ok)return;location.href=`part.html?id=${result.part.id}`}catch(err){alert("تعذر حفظ صورة القطعة. جرّب صورة أخرى أصغر.")}}
// النسخة الأساسية — بيتم استبدالها في customers/devices/inventory/requests.html
// بنسخة أغنى (تصنيفات ولوحة ملخص) في workshop-mini-simple-ui.js، وهي الشغالة
// فعليًا هناك. صفحات تانية (زي part.html) بتستخدم النسخة دي كما هي.
function renderParts(){let el=document.getElementById("partList");if(!el)return;let q=(partSearch?.value||"").toLowerCase();let a=arr(K.p).filter(p=>!p.archived&&(p.name+" "+p.code+" "+p.location).toLowerCase().includes(q));el.innerHTML=a.length?a.map(p=>{let pct=(+p.use||0)>0?(((+p.use||0)-(+p.buy||0))/(+p.use||0)*100):0;return `<div class="item ps-context-target" data-ps-title="قطعة ${esc(p.name)}"><div class="item-head"><a href="part.html?id=${p.id}"><b>📦 ${esc(p.name)}</b></a>${psActions("قطعة "+p.name)}<button type="button" class="danger-btn small-btn" onclick="deletePartRecord(&apos;${p.id}&apos;)">🗑️ حذف</button><span class="badge">${p.qty} قطعة</span></div><div>${esc(p.category)} • 📍 ${esc(p.location)||"—"}</div><div>شراء ${p.buy} ج • استخدام ${p.use} ج • 📈 ربح ${pct.toFixed(1)}%</div></div>`}).join(""):'<div class="item">لا توجد قطع.</div>'}
async function partProfile(){let el=document.getElementById("partProfile");if(!el)return;let p=arr(K.p).find(x=>x.id===new URLSearchParams(location.search).get("id"));if(!p){el.innerHTML="<div class='item'>القطعة غير موجودة.</div>";return}let moves=arr(K.m).filter(x=>x.partId===p.id).slice(-10).reverse();let profitVal=(+p.use||0)-(+p.buy||0),profitPct=(+p.use||0)>0?(profitVal/(+p.use||0)*100):0;el.innerHTML=`<div class="profile ps-context-target" data-ps-title="قطعة ${esc(p.name)}"><div class="page-head"><h1 class="profile-title">📦 ${esc(p.name)}</h1><div class="compact-actions"><button class="secondary" onclick="editPart('${p.id}')">✏️ تعديل</button>${p.archived?`<button class="primary" onclick="restorePartRecord('${p.id}')">↩️ إلغاء الأرشفة</button>`:`<button class="danger-btn" onclick="deletePartRecord('${p.id}')">🗑️ حذف</button>`}${psActions("قطعة "+p.name)}</div></div><div class="profile-grid"><div class="kv"><b>الكود</b>${esc(p.code)||"—"}</div><div class="kv"><b>التصنيف</b>${esc(p.category)}</div><div class="kv"><b>المكان</b>📍 ${esc(p.location)||"—"}</div><div class="kv"><b>الكمية</b>${p.qty}</div><div class="kv"><b>الحد الأدنى</b>${p.min}</div><div class="kv"><b>سعر الشراء</b>${p.buy} ج</div><div class="kv"><b>سعر الاستخدام</b>${p.use} ج</div><div class="kv"><b>📈 مكسب القطعة</b>${profitVal.toFixed(2)} ج (${profitPct.toFixed(1)}%)</div></div><div id="partProfilePhoto"></div><h2>🔄 آخر حركات المخزن</h2>${moves.length?moves.map(x=>`<div class="item">${esc(x.type)} • ${x.qty} • ${new Date(x.at).toLocaleString("ar-EG")}</div>`).join(""):"<div class='item'>لا توجد حركات.</div>"}</div>`;if(p.photo){let src=window.ImageStore?await window.ImageStore.resolveSrc(p.photo):p.photo;let ph=document.getElementById("partProfilePhoto");if(ph&&src)ph.innerHTML=`<img class="photo" src="${src}">`}}
