(function(){
  const money=n=>(+n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج';
  const dateKey=d=>window.dayKeyLocal?window.dayKeyLocal(d):'';
  const escR=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function range(){
    let from=document.getElementById('repFrom')?.value,to=document.getElementById('repTo')?.value;
    let now=new Date();
    if(!from)from=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;
    if(!to)to=dateKey(new Date(now.getFullYear(),now.getMonth()+1,0));
    return {from,to,start:new Date(from+'T00:00:00'),end:new Date(to+'T23:59:59.999')};
  }
  function inRangeDate(v,r){if(!v)return false;let d=new Date(v);return !Number.isNaN(d.getTime())&&d>=r.start&&d<=r.end}
  function inRangeDay(v,r){if(!v)return false;let k=String(v).slice(0,10);return k>=r.from&&k<=r.to}
  function orders(r){return arr(K.r).filter(x=>inRangeDate(x.createdAt,r)||inRangeDate(x.closedAt,r))}
  function expenses(r){return arr(K.e).filter(x=>inRangeDay(x.date,r))}
  function treasuryUntil(end){return arr(K.tr).filter(x=>!x.deleted&&new Date((x.date||'1970-01-01')+'T'+(x.time||'00:00'))<=end).reduce((a,x)=>a+(x.type==='in'?(+x.amount||0):-(+x.amount||0)),0)}
  function reportData(){
    const r=range(),os=orders(r),ex=expenses(r),cs=arr(K.c),ds=arr(K.d),ps=arr(K.p),ts=arr(K.tasks).filter(x=>inRangeDay(x.date,r)),tr=arr(K.tr).filter(x=>!x.deleted&&inRangeDay(x.date,r));
    const closedOrders=os.filter(x=>x.closed),labor=closedOrders.reduce((a,x)=>a+(+x.labor||0),0),partsSell=closedOrders.reduce((a,x)=>a+(+x.partsTotal||0),0),partsCost=closedOrders.reduce((a,x)=>a+(+x.partsCost||0),0),revenue=labor+partsSell,gross=revenue-partsCost,totalExp=ex.reduce((a,x)=>a+(+x.amount||0),0),net=gross-totalExp;
    const completed=os.filter(x=>x.closed||x.status==='مكتمل').length,open=os.filter(x=>!x.closed&&x.status!=='ملغي').length,waiting=os.filter(x=>x.partsWaiting===true||x.partsWaiting==='yes').length,workshop=os.filter(x=>x.executionPlace==='الورشة'||(x.workshopStatus&&x.workshopStatus!=='غير مطلوب'&&x.workshopStatus!=='تم التسليم')).length;
    return {r,os,ex,cs,ds,ps,ts,tr,labor,partsSell,partsCost,revenue,gross,totalExp,net,completed,open,waiting,workshop,low:ps.filter(p=>(+p.qty||0)<=(+p.min||0)).length,treasuryBalance:treasuryUntil(r.end)};
  }
  function section(title,body){return `<section class="panel report-section"><div class="report-section-head"><h2>${title}</h2></div>${body}</section>`}
  function cards(d){return `<div class="report-cards">
    <div class="report-card"><span>💰 الإيراد</span><b>${money(d.revenue)}</b></div><div class="report-card"><span>📈 المكسب قبل المصاريف</span><b>${money(d.gross)}</b></div><div class="report-card"><span>🧯 مصاريف التشغيل</span><b>${money(d.totalExp)}</b></div><div class="report-card"><span>✅ صافي المكسب</span><b>${money(d.net)}</b></div>
    <div class="report-card"><span>🛠️ أوامر الفترة</span><b>${d.os.length}</b></div><div class="report-card"><span>🔒 مكتملة/مغلقة</span><b>${d.completed}</b></div><div class="report-card"><span>📦 انتظار قطع</span><b>${d.waiting}</b></div><div class="report-card"><span>🏭 في الورشة</span><b>${d.workshop}</b></div>
  </div>`}
  function finance(d){return section('💰 التقرير المالي',`<div class="report-table-wrap"><table class="report-table-full"><tr><th>البند</th><th>القيمة</th><th>ملاحظة</th></tr><tr><td>🔨 المصنعية</td><td>${money(d.labor)}</td><td>من الأوامر المقفولة</td></tr><tr><td>🔧 قطع الغيار المحصلة</td><td>${money(d.partsSell)}</td><td>من الأوامر المقفولة</td></tr><tr><td>📦 تكلفة القطع</td><td>${money(d.partsCost)}</td><td>تكلفة القطع المستخدمة</td></tr><tr><td>💰 الإيراد</td><td>${money(d.revenue)}</td><td>مصنعية + قطع</td></tr><tr><td>📈 مكسب قبل المصاريف</td><td>${money(d.gross)}</td><td>الإيراد − تكلفة القطع</td></tr><tr><td>🧯 مصاريف التشغيل</td><td>${money(d.totalExp)}</td><td>لا تدخل في رصيد الخزنة</td></tr><tr class="report-total"><td>✅ صافي المكسب</td><td>${money(d.net)}</td><td>للنشاط</td></tr></table></div>`)}
  function ordersReport(d){let rows=d.os.slice().sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).map(o=>`<tr><td><a href="request.html?id=${o.id}">${escR(o.no)}</a></td><td>${escR(customerName(o.customerId))}</td><td>${escR(deviceName(o.deviceId))}</td><td>${escR(o.status)}</td><td>${o.executionPlace==='الورشة'?'🏭 الورشة':'🏠 العميل'}</td><td>${money(o.total)}</td><td>${money(o.deposit)}</td></tr>`).join('');return section('🛠️ تقرير أوامر الشغل',`<div class="report-table-wrap"><table class="report-table-full"><tr><th>الأمر</th><th>العميل</th><th>الجهاز</th><th>الحالة</th><th>المكان</th><th>الإجمالي</th><th>العربون</th></tr>${rows||'<tr><td colspan="7">لا توجد أوامر في الفترة.</td></tr>'}</table></div>`) }
  function customersReport(d){let counts={};d.os.forEach(o=>counts[o.customerId]=(counts[o.customerId]||0)+1);let top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,n])=>`<div class="report-list-row"><span><a href="customer.html?id=${id}">${escR(customerName(id))}</a></span><b>${n} أمر</b></div>`).join('');let newC=d.cs.filter(c=>inRangeDate(c.createdAt,d.r)).length;return section('👤 تقرير العملاء',`<div class="report-cards"><div class="report-card"><span>إجمالي العملاء</span><b>${d.cs.length}</b></div><div class="report-card"><span>عملاء جدد بالفترة</span><b>${newC}</b></div><div class="report-card"><span>عملاء تعاملوا بالفترة</span><b>${Object.keys(counts).length}</b></div></div><h3>⭐ أكثر العملاء تعاملًا في الفترة</h3><div class="report-list">${top||'<div class="report-empty">لا توجد تعاملات.</div>'}</div>`)}
  function devicesReport(d){let types={},brands={},serviced={};d.ds.forEach(x=>{types[x.type]=(types[x.type]||0)+1;brands[x.brand]=(brands[x.brand]||0)+1});d.os.forEach(o=>{if(o.deviceId)serviced[o.deviceId]=(serviced[o.deviceId]||0)+1});let typeRows=Object.entries(types).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="report-list-row"><span>${escR(k)}</span><b>${v}</b></div>`).join('');let brandRows=Object.entries(brands).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([k,v])=>`<div class="report-list-row"><span>${escR(k)}</span><b>${v}</b></div>`).join('');return section('🔧 تقرير الأجهزة',`<div class="report-cards"><div class="report-card"><span>إجمالي الأجهزة</span><b>${d.ds.length}</b></div><div class="report-card"><span>أنواع الأجهزة</span><b>${Object.keys(types).length}</b></div><div class="report-card"><span>الماركات</span><b>${Object.keys(brands).length}</b></div><div class="report-card"><span>أجهزة دخلت الخدمة بالفترة</span><b>${Object.keys(serviced).length}</b></div></div><div class="report-mini-grid"><div><h3>حسب النوع</h3><div class="report-list">${typeRows||'<div class="report-empty">لا توجد أجهزة.</div>'}</div></div><div><h3>أكثر الماركات</h3><div class="report-list">${brandRows||'<div class="report-empty">لا توجد أجهزة.</div>'}</div></div></div>`)}
  function inventoryReport(d){let stockValue=d.ps.reduce((a,p)=>a+(+p.qty||0)*(+p.buy||0),0),low=d.ps.filter(p=>(+p.qty||0)<=(+p.min||0));let usage={};arr(K.m).filter(m=>inRangeDate(m.at,d.r)).forEach(m=>usage[m.partId]=(usage[m.partId]||0)+(+m.qty||0));let usedRows=Object.entries(usage).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([id,n])=>{let p=d.ps.find(x=>x.id===id);return `<div class="report-list-row"><span><a href="part.html?id=${id}">${escR(p?.name||'قطعة محذوفة')}</a></span><b>${n}</b></div>`}).join('');let lowRows=low.slice(0,15).map(p=>`<div class="report-list-row report-danger"><span>${escR(p.name)} <small>(${p.qty}/${p.min})</small></span><b>${money((+p.qty||0)*(+p.buy||0))}</b></div>`).join('');return section('📦 تقرير المخزن',`<div class="report-cards"><div class="report-card"><span>قيمة المخزون بالتكلفة</span><b>${money(stockValue)}</b></div><div class="report-card"><span>أصناف منخفضة</span><b>${low.length}</b></div><div class="report-card"><span>إجمالي الأصناف</span><b>${d.ps.length}</b></div><div class="report-card"><span>حركات بالفترة</span><b>${arr(K.m).filter(m=>inRangeDate(m.at,d.r)).length}</b></div></div><div class="report-mini-grid"><div><h3>🔥 الأكثر حركة بالفترة</h3><div class="report-list">${usedRows||'<div class="report-empty">لا توجد حركات.</div>'}</div></div><div><h3>⚠️ الأصناف المنخفضة</h3><div class="report-list">${lowRows||'<div class="report-empty">لا توجد أصناف منخفضة.</div>'}</div></div></div>`)}
  function workshopReport(d){const current=arr(K.r).filter(o=>o.workshopStatus&&o.workshopStatus!=='غير مطلوب'&&o.workshopStatus!=='تم التسليم');const currentUnique=current.filter((o,i,a)=>a.findIndex(x=>x.id===o.id)===i);const delivered=d.os.filter(o=>o.workshopStatus==='تم التسليم');const rows=currentUnique.map(o=>`<tr><td><a href="request.html?id=${o.id}">${escR(o.no)}</a></td><td>${escR(customerName(o.customerId))}</td><td>${escR(deviceName(o.deviceId))}</td><td>${escR(o.workshopStatus||'غير مطلوب')}</td><td>${o.workshopAt?new Date(o.workshopAt).toLocaleString('ar-EG'):'—'}</td></tr>`).join('');const waiting=currentUnique.filter(o=>o.partsWaiting).length;return section('🏭 تقرير الورشة',`<div class="report-cards"><div class="report-card"><span>أجهزة/أوامر داخل الورشة الآن</span><b>${currentUnique.length}</b></div><div class="report-card"><span>انتظار قطع</span><b>${waiting}</b></div><div class="report-card"><span>تم التسليم بالفترة</span><b>${delivered.length}</b></div></div><div class="report-table-wrap"><table class="report-table-full"><tr><th>الأمر</th><th>العميل</th><th>الجهاز</th><th>حالة الورشة</th><th>آخر تحديث</th></tr>${rows||'<tr><td colspan="5">لا توجد أجهزة داخل الورشة حاليًا.</td></tr>'}</table></div>`) }
  function treasuryReport(d){let ins=d.tr.filter(x=>x.type==='in').reduce((a,x)=>a+(+x.amount||0),0),outs=d.tr.filter(x=>x.type==='out').reduce((a,x)=>a+(+x.amount||0),0);let rows=d.tr.slice().sort((a,b)=>String(b.date+b.time).localeCompare(String(a.date+a.time))).map(x=>`<tr><td>${escR(x.date||'—')}</td><td>${escR(x.time||'—')}</td><td>${x.type==='in'?'➕ وارد':'➖ صرف'}</td><td>${escR(x.reason||'—')}</td><td>${escR(x.counterparty||'')}</td><td>${escR(x.place||'')}</td><td>${money(x.amount)}</td></tr>`).join('');return section('💵 تقرير الخزنة المستقلة',`<div class="hint">الخزنة منفصلة عن حسابات أوامر الشغل وقطع الغيار ومصاريف التشغيل. الأرقام التالية لحركات درج الخزنة فقط.</div><div class="report-cards"><div class="report-card"><span>وارد الفترة</span><b>${money(ins)}</b></div><div class="report-card"><span>صرف الفترة</span><b>${money(outs)}</b></div><div class="report-card"><span>صافي حركة الفترة</span><b>${money(ins-outs)}</b></div><div class="report-card"><span>رصيد الدرج حتى نهاية الفترة</span><b>${money(d.treasuryBalance)}</b></div></div><div class="report-table-wrap"><table class="report-table-full"><tr><th>التاريخ</th><th>الوقت</th><th>الحركة</th><th>السبب</th><th>لمن/من</th><th>المكان</th><th>المبلغ</th></tr>${rows||'<tr><td colspan="7">لا توجد حركات خزنة في الفترة.</td></tr>'}</table></div>`)}
  function tasksReport(d){let today=dateKey(new Date()),open=d.ts.filter(t=>!t.completed).length,done=d.ts.filter(t=>t.completed).length,over=d.ts.filter(t=>!t.completed&&t.date&&t.date<today).length;return section('📋 تقرير المهام والمتابعة',`<div class="report-cards"><div class="report-card"><span>مهام الفترة</span><b>${d.ts.length}</b></div><div class="report-card"><span>مكتملة</span><b>${done}</b></div><div class="report-card"><span>مفتوحة</span><b>${open}</b></div><div class="report-card"><span>متأخرة</span><b>${over}</b></div></div><div class="report-list">${d.ts.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(t=>`<div class="report-list-row"><span>${t.completed?'✅':'📋'} ${escR(t.title)} <small>• ${escR(t.date||'')}</small></span><b>${escR(t.priority||'عادية')}</b></div>`).join('')||'<div class="report-empty">لا توجد مهام في الفترة.</div>'}</div>`)}
  function render(){const host=document.getElementById('reportsHost');if(!host)return;const d=reportData();document.getElementById('reportPeriodLabel').textContent=`من ${d.r.from} إلى ${d.r.to}`;host.innerHTML=cards(d)+finance(d)+ordersReport(d)+customersReport(d)+devicesReport(d)+inventoryReport(d)+workshopReport(d)+treasuryReport(d)+tasksReport(d)}
  function preset(kind){let now=new Date(),from,to;if(kind==='today'){from=to=dateKey(now)}else if(kind==='week'){let day=now.getDay()||7;let s=new Date(now);s.setDate(now.getDate()-day+1);let e=new Date(s);e.setDate(s.getDate()+6);from=dateKey(s);to=dateKey(e)}else if(kind==='month'){from=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-01`;to=dateKey(new Date(now.getFullYear(),now.getMonth()+1,0))}else{return}document.getElementById('repFrom').value=from;document.getElementById('repTo').value=to;render()}
  document.addEventListener('DOMContentLoaded',()=>{if(!document.getElementById('reportsHost'))return;preset('month');document.getElementById('repApply').onclick=render;document.getElementById('repToday').onclick=()=>preset('today');document.getElementById('repWeek').onclick=()=>preset('week');document.getElementById('repMonth').onclick=()=>preset('month');});
})();
